module top_module(
    input reset, clk,
    
    // --- NEW: Expose PC and Instruction for the Driver ---
    output [31:0] pc_out,    // Was internal 'PC'
    input  [31:0] instr_in,  // Was internal 'Instr' generated by IM1
    
    // --- NEW: Expose Data Memory Bus for the DataSlave ---
    output        mem_write, // Was internal 'MemWrite'
    output [31:0] alu_result, // This is the Address (DataAddr)
    output [31:0] write_data,// Data to be written (WriteData)
    input  [31:0] read_data // Data read from memory (ReadData)
);

    // 1. Internal Wires (Same as before, but mapped to ports)
    //Removed Wires: MemWrite;
    //Added ports: pc_out, instr_in, mem_write, alu_result, write_data, read_data;
    wire Zero, Carry, Referee; 
    wire RegWrite, ALUSrc, RegSrc;
    wire [1:0] ResultSrc, PCSrc;
    wire [2:0] ImmSrc;
    wire [3:0] ALUControl;
    wire Branch, Jump, JumpReg;

    // Wire declarations for internal connections
    wire [31:0] PC, Instr, DataAddr, WriteData, ReadData;

    // mem_write is already an output port, but we need to connect control path to it
    wire internal_mem_write;


    // 2. Map Ports to Internal Wires
    assign pc_out = PC;        // Send PC to Testbench
    assign Instr  = instr_in;  // Receive Instruction from Testbench

    // Map Memory ports
    assign alu_result = DataAddr; 
    assign write_data = WriteData;
    assign ReadData   = read_data; // Receive Data from Testbench

    // Connect internal mem_write to output port
    assign mem_write = internal_mem_write;

    // 3. Instantiation: DATAPATH
    datapath DP1(
        .RegWrite(RegWrite), .ALUSrc(ALUSrc), .PCSrc(PCSrc), .RegSrc(RegSrc), 
        .ImmSrc(ImmSrc), .ResultSrc(ResultSrc), .ALUControl(ALUControl), 
        .clk(clk), .reset(reset), 
        .RD(ReadData), // Input from Port
        .Instr(Instr), // Input from Port
        .Zero(Zero), .Carry(Carry), .Referee(Referee), 
        .PC(PC),       // Output to Port
        .WD(WriteData),// Output to Port
        .ALUResult(DataAddr), // Output to Port
        .display_data(display_data)
    );
  
    // 4. Instantiation: CONTROLPATH
    controlpath CP1(
        .Zero(Zero), .Carry(Carry), .Referee(Referee), 
        .Instr(Instr), 
        .MemWrite(internal_mem_write), // Connect to wire, which goes to port
        .RegWrite(RegWrite), .ALUSrc(ALUSrc), .PCSrc(PCSrc), .RegSrc(RegSrc), 
        .ALUControl(ALUControl), .ResultSrc(ResultSrc), .ImmSrc(ImmSrc), 
        .Branch(Branch), .Jump(Jump), .JumpReg(JumpReg)
    );

    // 5. REMOVED MODULES
    // We deleted Instruction_Memory IM1 -> Replaced by 'driver' in testbench
    // We deleted Data_Memory DM1       -> Replaced by 'data_slave' in testbench

endmodule